---
language: python
python: "2.7"
sudo: false

addons:
  apt:
    packages:
      - python-pip
      - curl

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../\nhost_key_checking = False' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local
  - curl -s --fail http://localhost:8500 &>/dev/null

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
