---

- name: prerequisite local
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: prerequisite local
      local_action: package name=ca-certificates state=latest

- name: prerequisite
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python
  pre_tasks:
    - name: prerequisite
      package: name={{ item }} state=latest
      with_items:
        - iproute
        - rsyslog
        - ca-certificates
        - sudo

- name: run the main role
  hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python
  roles:
    - role: ansible-consul
      consul_version: 1.2.2
      consul_config_validate: "{{ consul_user_home }}/bin/consul validate -config-format=json %s"
      consul_configs:
        main:
          bind_addr: 0.0.0.0
          client_addr: 0.0.0.0
          node_name: "{{ ansible_hostname }}"
          data_dir: "{{ consul_data_dir }}"
          encrypt: "chohLoix1mec9Wooye3shoh3"
          enable_syslog: true
          datacenter: automium
          server: true
          ui: true
