---
- hosts: all
  gather_facts: False
  tasks:
  - name: install ansible prerequisite (python)
    raw: test -e /usr/bin/python || ( apt update -y && apt install python-minimal -y )

- hosts: all
  gather_facts: true
  tasks:
  - name: install basetools
    apt:
      name: [vim, ca-certificates, htop, unzip, curl, iproute2]
      update_cache: yes
      state: present
